
[[skills]]
id = "architecture"
title = "Architecture"
content = """
Certified in [TOGAF® 9 Certified](https://www.credly.com/badges/c6fbe702-bf9d-4a70-a50c-1d52b1e6c6a1/public_url),
[ArchiMate® 3 Practitioner](https://www.credly.com/badges/fca71178-57a0-4cdb-92f4-35f1034895cc/public_url) and
as an [AWS Certified Solutions Architect - Associate](https://www.credly.com/badges/78c60816-fa66-4949-b7fd-90c27d0d1638/public_url),
I assist both the team and the organization in pinpointing, strategizing, and executing solutions that elevate business results.
"""

[[skills]]
id = "agile"
title = "Agile-Certified"
content = """
Holding [PSM I](https://www.credly.com/badges/a36b9c1b-696d-4031-8f34-425555f9aa19/public_url),
[PSPO I](https://www.credly.com/badges/7ef29408-251e-4737-9d1b-dc3aaec814e4/public_url),
[PSD I](https://www.credly.com/badges/16b079cb-6481-48c1-a925-0f89f4feb445/public_url) certifications,
I serve as a guiding force for both the team and the organization, optimizing interactions to enhance value.
"""

[[skills]]
id = "devops"
title = "Devops"
content = """
As a [Certified Kubernetes Application Developer](https://www.credly.com/badges/5bdad9b7-84bf-4eba-b173-65d34e52b24d/public_url),
I specialize in constructing robust delivery pipelines and ensuring transparent deployment environments.
My expertise aids the team in reducing operational hazards.
"""

[[skills]]
id = "development"
title = "Development"
content = """
Boasting over 15 years in software development and profound expertise in Java and JavaScript/Typescript applications,
whether on bare-metal servers or cloud platforms, I guide the team in crafting robust, secure,
and scalable containerized solutions, alongside versatile, comprehensible, and testable web applications.
"""
